name: auto_input_box
description: "A Flutter package for dynamic input boxes with auto-suggestions and overlay-based UI components."
version: 0.0.1
homepage: https://github.com/muhsindev4/auto_input_box
repository: https://github.com/muhsindev4/auto_input_box
screenshots:
  - https://raw.githubusercontent.com/muhsindev4/auto_input_box/refs/heads/main/image.png
documentation: https://github.com/muhsindev4/auto_input_box/wiki
# 5 topics to better categorize your project
topics:
  - flutter
  - widget
  - autocomplete
  - input
  - overlay

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Optional: This section helps with package publishing and includes a default license
license: MIT

